# This is a basic workflow to help you get started with Actions

name: CI Marvel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Linux:
    name: Testes com Insomnia Udemy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.6
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Installing inso
        run: npm install -g insomnia-inso
      - name: Lint
        run: inso lint spec "Comics" --ci
      - name: Running Tests Suites
        run: inso run test "Comics" --env "Produção" --ci
      - name: Generating the config
        run: inso generate config "Comics" --type declarative --ci
